defaults:
  - model/encoder: noposplat
  - model/decoder: splatting_cuda
  - loss: [mse]

wandb:
  project: noposplat
  entity: scene-representation-group
  name: placeholder
  mode: disabled

mode: train

#dataset:
#  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 8
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 8
    seed: 2345
  val:
    num_workers: 4
    persistent_workers: true
    batch_size: 8
    seed: 3456

optimizer:
  lr: 1.5e-4
  warm_up_steps: 2000
  backbone_lr_multiplier: 0.1

checkpointing:
  load: null
  every_n_train_steps: 5000
  save_top_k: 1
  save_weights_only: true

train:
  depth_mode: null
  output_path: ./outputs/train
  extended_visualization: false
  print_log_every_n_steps: 50
  distiller: ''
  distill_max_steps: 1000000

test:
  output_path: ./outputs/test
  align_pose: false
  pose_align_steps: 100
  rot_opt_lr:  0.005
  trans_opt_lr:  0.005
  compute_scores: true
  save_image: true
  save_video: false
  save_compare: false

seed: 111123

trainer:
  max_steps: 25000
  gradient_clip_val: 0.5
  num_nodes: 1
  check_val_every_n_epoch: 1
  max_epochs: 10
  enable_progress_bar: true
  num_sanity_val_steps: 10

hydra:
  run:
    dir: outputs/train/exp_${wandb.name}/
