defaults:
  - base_dataset
  - view_sampler: bounded

name: aer_grd_drone_pi3

input_image_shape: [128, 128]
original_image_shape: [1080, 1920]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e10
max_fov: 100.0

GrdImg_H: 256
GrdImg_W: 512
