defaults:
  - base_dataset
  - view_sampler: bounded

name: kitti
roots: [/data/dataset/KITTI]
# file: './kitti/train_files.txt'
file: './kitti/test1_files.txt'

input_image_shape: [256, 256]
original_image_shape: [256, 1024]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e10
max_fov: 100.0
